spring:
  application:
    name: cervejaria-app
  session:
    timeout: 1800
  datasource:
    url: jdbc:postgresql://localhost:5432/acme
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
server:
  port: 8080