apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cervejaria
  name: cervejaria-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage