apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cervejaria
  name: cervejaria-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /Users/leonardogloria/Documents/Projetos/Infnet/pos-graduacao/devops/projeto_final/cervejaria-acme/k8s/data

