apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cervejaria
  name: cervejaria-acme
  labels:
    app: cervejaria-acme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cervejaria-acme
  template:
    metadata:
      name: cervejaria-acme
      labels:
        app: cervejaria-acme
    spec:
      containers:
        - image: leogloriainfnet/cervejaria:latest
          name: cervejaria-acme
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 3
            httpGet:
              port: 8080
              path: /acutuator/health
          livenessProbe:
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              port: 8080
              path: /actuator/health