apiVersion: v1
kind: Service
metadata:
  name: cervejaria-acme-svc
  namespace: cervejaria
spec:
  selector:
    app: cervejaria-acme
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
  type: NodePort