apiVersion: v1
kind: Service
metadata:
  namespace: cervejaria
  name: redis-monitoramento-svc
spec:
  selector:
    app: redis
  ports:
    - port: 9121
      targetPort: 9121
      protocol: TCP
      nodePort: 30007
  type: NodePort