name: Deploy To Prod
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted
    steps:
#      - name: Config GIT
#        run: |
#          git config user.name "githubActions[bot]"
#          git config user.email "bot@no-reply.com"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Exibir ENVS
        run: |
          java -version
          mvn -version
      - name: Limpar Diretorio
        run: mvn clean
      - name: Executar testes
        run: mvn test
      - name: Incrementar Versao
        id: increment-version
        run: |
          current=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Versão atual: $current"
          
          IFS='.' read -r major minor patch <<< "$current"
          new_major=$((major + 1))
          next="$new_major.$minor.$patch"
          echo "Nova versão: $next"
          
          mvn versions:set -DnewVersion=$next
          new_version=$next" >> "$GITHUB_OUTPUT
          echo "new_version=$next" >> "$GITHUB_OUTPUT"

      - name: Build do Projeto
        run: mvn package -DskipTests
      - name: Confirmar versao do codigo
        run: | 
          echo "nova versão é: ${{ steps.increment-version.new_version }}"
#      - name: Commit do POM
#        run: |
#          git add pom.xml
#          git commit -m "Alterando a versao do projeto"
#          git push origin main

      - name: copiar artefato
        run: |
          cp target/*.jar docker/app.jar
      - name: Build Docker Image
        run: docker build . -f docker/Dockerfile -t cervejaria:4.0
      - name: Criar TAG
        run: docker tag cervejaria:4.0 leogloriainfnet/cervejaria:latest
      - name: Criar TAG
        run: docker tag cervejaria:4.0 leogloriainfnet/cervejaria:4.0
      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Docker Push
        run: docker push leogloriainfnet/cervejaria:latest
      - name: Docker Push
        run: docker push leogloriainfnet/cervejaria:4.0


